alias "cls"="clear"
alias "nix-edit"="sudo vim /etc/nixos/configuration.nix; sudo cp /etc/nixos/configuration.nix /home/peridot/dotfiles/configuration.nix"
alias "nix-refresh"="sudo nixos-rebuild switch"
alias "nix-clean"="sudo nix-collect-garbage -d"
eval "$(direnv hook bash)"
alias "gs"="git status"
alias "ga"="git add"
alias "gc"="git commit -m"
